package main

import (
	"context"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

func TestMapMirror_HTTPPreservesUnexpectedExistingRegularFile(t *testing.T) {
	db, err := OpenDB(filepath.Join(t.TempDir(), "map.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	now := time.Date(2026, 9, 20, 12, 0, 0, 0, time.UTC)
	store := NewWorkstreamStore(db, func() time.Time { return now }, time.UTC)
	vault := t.TempDir()
	worker := NewMirrorWorker(store, MirrorWorkerConfig{Root: vault, Now: func() time.Time { return now }})
	store.SetAfterCommit(worker.Wake)
	mux := mapMirrorFaultMux(store, worker)

	created := postMapCommand(t, mux, WorkstreamCommand{OperationID: "collision-create", Action: "create_workstream", Workstream: WorkstreamInput{Name: "Collision", Outcome: "Keep unrelated note"}})
	target := filepath.Join(vault, "workstreams", created.WorkstreamID+".md")
	if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
		t.Fatal(err)
	}
	const unrelated = "this file was not generated by Cockpit\n"
	if err := os.WriteFile(target, []byte(unrelated), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := worker.Drain(context.Background()); err != nil {
		t.Fatal(err)
	}
	if got := string(mustReadFile(t, target)); got != unrelated {
		t.Fatalf("unexpected target was overwritten: %q", got)
	}
	view := getMapData(t, mux, created.WorkstreamID)
	if view.Selected == nil || view.Selected.Mirror.Status != "conflict" || view.Selected.Mirror.LastSuccessRevision != 0 {
		t.Fatalf("collision mirror state=%+v, want unsynced conflict", view.Selected)
	}
	historyAtConflict := view.Timeline.Total
	for attempt := 0; attempt < 2; attempt++ {
		retryMirrorHTTP(t, mux, MirrorKey{EntityType: "workstream", EntityID: created.WorkstreamID})
		if err := worker.Drain(context.Background()); err != nil {
			t.Fatal(err)
		}
		view = getMapData(t, mux, created.WorkstreamID)
		if view.Selected == nil || view.Selected.Mirror.Status != "conflict" || view.Timeline.Total != historyAtConflict {
			t.Fatalf("conflict retry %d changed operational history/state: %+v timeline=%d want=%d", attempt+1, view.Selected, view.Timeline.Total, historyAtConflict)
		}
	}
}

func TestMapMirror_HTTPRejectsRootAndManagedDirectorySymlinks(t *testing.T) {
	for _, tc := range []struct {
		name  string
		setup func(t *testing.T, vault, outside string) string
	}{
		{
			name: "root",
			setup: func(t *testing.T, vault, outside string) string {
				t.Helper()
				if err := os.Symlink(outside, vault); err != nil {
					t.Fatal(err)
				}
				return outside
			},
		},
		{
			name: "managed-directory",
			setup: func(t *testing.T, vault, outside string) string {
				t.Helper()
				if err := os.MkdirAll(vault, 0o700); err != nil {
					t.Fatal(err)
				}
				if err := os.Symlink(outside, filepath.Join(vault, "workstreams")); err != nil {
					t.Fatal(err)
				}
				return outside
			},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			db, err := OpenDB(filepath.Join(t.TempDir(), "map.db"))
			if err != nil {
				t.Fatal(err)
			}
			defer db.Close()
			now := time.Date(2026, 9, 20, 12, 0, 0, 0, time.UTC)
			store := NewWorkstreamStore(db, func() time.Time { return now }, time.UTC)
			base := t.TempDir()
			vault := filepath.Join(base, "vault")
			outside := filepath.Join(base, "outside")
			if err := os.Mkdir(outside, 0o700); err != nil {
				t.Fatal(err)
			}
			outside = tc.setup(t, vault, outside)
			worker := NewMirrorWorker(store, MirrorWorkerConfig{Root: vault, Now: func() time.Time { return now }})
			store.SetAfterCommit(worker.Wake)
			mux := mapMirrorFaultMux(store, worker)

			created := postMapCommand(t, mux, WorkstreamCommand{OperationID: "symlink-" + tc.name, Action: "create_workstream", Workstream: WorkstreamInput{Name: "Safe paths", Outcome: "Never leave vault"}})
			if err := worker.Drain(context.Background()); err != nil {
				t.Fatal(err)
			}
			if entries, err := os.ReadDir(outside); err != nil || len(entries) != 0 {
				t.Fatalf("mirror wrote outside configured root: entries=%v err=%v", entries, err)
			}
			view := getMapData(t, mux, created.WorkstreamID)
			if view.Selected == nil || view.Selected.Mirror.Status != "conflict" {
				t.Fatalf("symlink mirror state=%+v, want conflict", view.Selected)
			}
		})
	}
}

func TestMapMirror_HTTPReferenceReattachKeepsStableIDAndRefreshesExports(t *testing.T) {
	db, err := OpenDB(filepath.Join(t.TempDir(), "map.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	now := time.Date(2026, 9, 20, 12, 0, 0, 0, time.UTC)
	store := NewWorkstreamStore(db, func() time.Time { return now }, time.UTC)
	vault := t.TempDir()
	worker := NewMirrorWorker(store, MirrorWorkerConfig{Root: vault, Now: func() time.Time { return now }})
	store.SetAfterCommit(worker.Wake)
	mux := mapMirrorFaultMux(store, worker)

	ws := postMapCommand(t, mux, WorkstreamCommand{OperationID: "reattach-workstream", Action: "create_workstream", Workstream: WorkstreamInput{Name: "References", Outcome: "Keep source context"}})
	ref := postMapCommand(t, mux, WorkstreamCommand{OperationID: "reattach-reference", Action: "create_item", WorkstreamID: ws.WorkstreamID, Item: WorkstreamItemInput{Kind: "reference", Title: "Design RFC", SourceKind: "rfc", SourceURL: "https://example.com/design/rfc#decisions"}})
	if err := worker.Drain(context.Background()); err != nil {
		t.Fatal(err)
	}
	detached := postMapCommand(t, mux, WorkstreamCommand{OperationID: "reattach-detach", Action: "detach_item", WorkstreamID: ws.WorkstreamID, ItemID: ref.ItemID, ExpectedRevision: ref.Revision, Confirm: true})
	if err := worker.Drain(context.Background()); err != nil {
		t.Fatal(err)
	}
	reattached := postMapCommand(t, mux, WorkstreamCommand{OperationID: "reattach-reference-again", Action: "create_item", WorkstreamID: ws.WorkstreamID, Item: WorkstreamItemInput{Kind: "reference", Title: "Renamed input must not replace existing reference", SourceKind: "rfc", SourceURL: "https://example.com/design/rfc#decisions"}})
	if reattached.ItemID != ref.ItemID || reattached.Revision != detached.Revision+1 {
		t.Fatalf("reattach=%+v, want stable item %q at revision %d", reattached, ref.ItemID, detached.Revision+1)
	}
	if err := worker.Drain(context.Background()); err != nil {
		t.Fatal(err)
	}
	item := string(mustReadFile(t, filepath.Join(vault, "engineering", ref.ItemID+".md")))
	parent := string(mustReadFile(t, filepath.Join(vault, "workstreams", ws.WorkstreamID+".md")))
	if !strings.Contains(item, `id: "`+ref.ItemID+`"`) || !strings.Contains(item, "Design RFC") || strings.Contains(item, "Renamed input") {
		t.Fatalf("item export did not retain latest stable reference identity:\n%s", item)
	}
	if !strings.Contains(parent, "../engineering/"+ref.ItemID+".md") {
		t.Fatalf("parent export did not include reattached reference:\n%s", parent)
	}
}

func TestMapMirror_HTTPStaleAcknowledgmentCannotSyncNewerRevision(t *testing.T) {
	db, err := OpenDB(filepath.Join(t.TempDir(), "map.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	now := time.Date(2026, 9, 20, 12, 0, 0, 0, time.UTC)
	store := NewWorkstreamStore(db, func() time.Time { return now }, time.UTC)
	vault := t.TempDir()
	race := &mirrorAckRaceStore{MirrorStore: store}
	worker := NewMirrorWorker(race, MirrorWorkerConfig{Root: vault, Now: func() time.Time { return now }})
	store.SetAfterCommit(worker.Wake)
	mux := mapMirrorFaultMux(store, worker)
	created := postMapCommand(t, mux, WorkstreamCommand{OperationID: "ack-race-create", Action: "create_workstream", Workstream: WorkstreamInput{Name: "Before acknowledgement", Outcome: "Never falsely sync"}})

	race.beforeAck = func() {
		postMapCommand(t, mux, WorkstreamCommand{OperationID: "ack-race-edit", Action: "edit_workstream", WorkstreamID: created.WorkstreamID, ExpectedRevision: created.Revision, Workstream: WorkstreamInput{Name: "After acknowledgement race", Outcome: "Newest export wins"}})
	}
	race.afterAck = func() {
		view := getMapData(t, mux, created.WorkstreamID)
		if view.Selected == nil || view.Selected.Revision != 2 || view.Selected.Mirror.Status == "synced" || view.Selected.Mirror.LastSuccessRevision >= view.Selected.Revision {
			t.Errorf("stale acknowledgement falsely synced newer revision: %+v", view.Selected)
		}
	}
	if err := worker.Drain(context.Background()); err != nil {
		t.Fatal(err)
	}
	view := getMapData(t, mux, created.WorkstreamID)
	if view.Selected == nil || view.Selected.Mirror.Status != "synced" || view.Selected.Mirror.LastSuccessRevision != view.Selected.Revision {
		t.Fatalf("latest revision did not subsequently sync: %+v", view.Selected)
	}
	if got := string(mustReadFile(t, filepath.Join(vault, "workstreams", created.WorkstreamID+".md"))); !strings.Contains(got, "After acknowledgement race") || strings.Contains(got, "Before acknowledgement") {
		t.Fatalf("vault did not end at newest revision:\n%s", got)
	}
}

type mirrorAckRaceStore struct {
	MirrorStore
	mu                  sync.Mutex
	beforeAck, afterAck func()
	fired               bool
}

func (s *mirrorAckRaceStore) AckMirrorWrite(ctx context.Context, key MirrorKey, revision int64, sum string, at time.Time) error {
	s.mu.Lock()
	before, after := s.beforeAck, s.afterAck
	if s.fired || before == nil {
		s.mu.Unlock()
		return s.MirrorStore.AckMirrorWrite(ctx, key, revision, sum, at)
	}
	s.fired = true
	s.mu.Unlock()
	before()
	err := s.MirrorStore.AckMirrorWrite(ctx, key, revision, sum, at)
	if err == nil && after != nil {
		after()
	}
	return err
}

func mapMirrorFaultMux(store *WorkstreamStore, worker *MirrorWorker) *http.ServeMux {
	s := &server{baseCtx: context.Background(), workstreams: store, mirror: worker}
	mux := http.NewServeMux()
	s.routes(mux)
	return mux
}
